language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: almilo@almilo.es
  api_key:
    secure: pkKWjqzr4EI0kBlnL2GrggQNrWuXw8QbpA88UpJfUd5dtF8eR5L2J5CY48n/R2Xl1liAuUm11pf7JN1eLYgUI3fjdj98giTVdzMjsRTRzrqcHpXrXKsfiXwC60IRs0Otyg/cBkXPWK34DlgsEoYpAb8Td81pRT7o63/y2/vpoMs=
  on:
    tags: true
    all_branches: true
